/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'snacks' : IDL.Null,
  'namkeen' : IDL.Null,
  'beverages' : IDL.Null,
  'sweets' : IDL.Null,
});
export const Unit = IDL.Variant({ 'per_kg' : IDL.Null, 'single' : IDL.Null });
export const ProductId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'unit' : Unit,
  'description' : IDL.Text,
  'photoUrl' : IDL.Text,
  'available' : IDL.Bool,
  'category' : Category,
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, Category, IDL.Text, IDL.Nat, IDL.Bool, Unit, IDL.Text],
      [ProductId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'debugPrintProducts' : IDL.Func([], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'editProduct' : IDL.Func(
      [
        ProductId,
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Nat,
        IDL.Bool,
        Unit,
        IDL.Text,
      ],
      [],
      [],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'snacks' : IDL.Null,
    'namkeen' : IDL.Null,
    'beverages' : IDL.Null,
    'sweets' : IDL.Null,
  });
  const Unit = IDL.Variant({ 'per_kg' : IDL.Null, 'single' : IDL.Null });
  const ProductId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'unit' : Unit,
    'description' : IDL.Text,
    'photoUrl' : IDL.Text,
    'available' : IDL.Bool,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, Category, IDL.Text, IDL.Nat, IDL.Bool, Unit, IDL.Text],
        [ProductId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'debugPrintProducts' : IDL.Func([], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'editProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Nat,
          IDL.Bool,
          Unit,
          IDL.Text,
        ],
        [],
        [],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };